LARGURA_METEORO_1		EQU	1
ALTURA_METEORO_1		EQU 1
LARGURA_METEORO_2		EQU	2
ALTURA_METEORO_2		EQU 2
LARGURA_METEORO_3		EQU	3
ALTURA_METEORO_3		EQU 3
LARGURA_METEORO_4		EQU	4
ALTURA_METEORO_4		EQU 4
LARGURA_METEORO_5		EQU	5
ALTURA_METEORO_5		EQU 5

COR_METEORO_INDISTINTO 	EQU 08FFFH
COR_METEORO_BOM			EQU 0F0F0H
COR_METEORO_MAU			EQU 0FF00H

DEF_METEORO_1:
	WORD	LARGURA_METEORO_1, ALTURA_METEORO_1
	WORD	COR_METEORO_INDISTINTO

DEF_METEORO_2:
	WORD	LARGURA_METEORO_2, ALTURA_METEORO_2
	WORD	COR_METEORO_INDISTINTO, COR_METEORO_INDISTINTO
	WORD	COR_METEORO_INDISTINTO, COR_METEORO_INDISTINTO

DEF_METEORO_BOM_3:
	WORD	LARGURA_METEORO_3, ALTURA_METEORO_3
	WORD	0, COR_METEORO_BOM, 0
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	0, COR_METEORO_BOM, 0

DEF_METEORO_BOM_4:
	WORD	LARGURA_METEORO_4, ALTURA_METEORO_4
	WORD	0, COR_METEORO_BOM, COR_METEORO_BOM, 0
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	0, COR_METEORO_BOM, COR_METEORO_BOM, 0

DEF_METEORO_BOM_5:
	WORD	LARGURA_METEORO_5, ALTURA_METEORO_5
	WORD	0, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, 0
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM
	WORD	0, COR_METEORO_BOM, COR_METEORO_BOM, COR_METEORO_BOM, 0

DEF_METEORO_MAU_3:
	WORD	LARGURA_METEORO_3, ALTURA_METEORO_3
	WORD	COR_METEORO_MAU, 0, COR_METEORO_MAU
	WORD	0, COR_METEORO_MAU, 0
	WORD	COR_METEORO_MAU, 0, COR_METEORO_MAU

DEF_METEORO_MAU_4:
	WORD	LARGURA_METEORO_4, ALTURA_METEORO_4
	WORD	COR_METEORO_MAU, 0, 0, COR_METEORO_MAU
	WORD	COR_METEORO_MAU, 0, 0, COR_METEORO_MAU
	WORD	0, COR_METEORO_MAU, COR_METEORO_MAU, 0
	WORD	COR_METEORO_MAU, 0, 0, COR_METEORO_MAU

DEF_METEORO_MAU_5:
	WORD	LARGURA_METEORO_5, ALTURA_METEORO_5
	WORD	COR_METEORO_MAU, 0, 0, 0, COR_METEORO_MAU
	WORD	COR_METEORO_MAU, 0, COR_METEORO_MAU, 0, COR_METEORO_MAU
	WORD	0, COR_METEORO_MAU, COR_METEORO_MAU, COR_METEORO_MAU, 0
	WORD	COR_METEORO_MAU, 0, COR_METEORO_MAU, 0, COR_METEORO_MAU
	WORD	COR_METEORO_MAU, 0, 0, 0, COR_METEORO_MAU